### PR TITLE
Names

### PR DESCRIPTION
**Pull request by davidbanham**
Ref #2

### CODE REVIEW

**Comment by nwinch** [comment]
Do we need controllers anymore?

**Comment by nwinch** [comment]
@davidbanham Review done.  LGTM, with just on question.

**Comment by davidbanham** [comment]
The controllers are definitely a bit of an awkward stepchild now. Apologies for the lack of words in this PR. I don't actually see this code as final, but as something that can inform our discussion in #4.

This commit basically implements Nikolay's suggested split as I see it:

https://github.com/Prismatik/redbeard/pull/91/commits/28047caab7d84b45e09fdb1cc22031c7f5b19d10

And this commit then implements Nick's suggestion on top of it:

https://github.com/Prismatik/redbeard/pull/91/commits/3b4d6e34c61605d1ec1ffe850a28c270ba1f78bc

I don't think the controllers serve a good purpose in the form they take in the second commit. I think we either pull some of the logic from models back into controllers, or we just `git revert 3b4d6e` and carry on with our lives. I'm in favour of the latter.

**Comment by MadRabbit** [comment]
Makes sense to me your controllers are basically models at the moment. I'm happy with the change.

@nwinch as for controllers. i think this depends on a case. node routes are technically what other projects call a "front controller". and what is called "controllers" in a node app is normally where pieces of more complex business logic go.

like for example you have a complex user registration process. you need to save a user in a database, you need to issue a welcome email, maybe spawn some dependent models, like a test product or something. this is what controllers are for.

basically the principle is like this: 

1. your routes should be very shallow, they should just be concerned with parsing requests and building responses. 
2. your models should be pretty shallow too, it should be basically a CRUD interface.
3. all business logic that happens in between routes and models goes in "controllers"

So, some projects might have controllers some might not. depends on how complex the logic is. I think, sometimes it's okay to add a few methods on a model and call it a day.

Also. The word "controllers" is a bit confusing in this context, because it is normally associated with HTTP CRUD controllers. Technically this layer is called the "services" or "business logic" layer. Basically because "services" don't impose a CRUD interface on a controller, which don't always make sense in case of business logic. Long story short, I prefer to name the folder `services` instead of `controllers`

**Comment by davidbanham** [comment]
> like for example you have a complex user registration process. you need to save a user in a database, you need to issue a welcome email, maybe spawn some dependent models, like a test product or something. this is what controllers are for.

This is the thing that leant me back towards leaving the controllers in place. It's a decision that would be easy to make on an individual project. In a scaffold like this it's a little tricky. I suppose what we want to do at least initially is design for the highest common denominator of complexity. That implies that we want to leave the controller in place in order to give people a spot to put that complex business logic when/if it pops up. There's nothing stopping you just deleting the controllers folder and calling the model directly from the routes on a super simple project.

**Comment by MadRabbit** [comment]
a fair point. rails was notoriously good at creating empty folders and it helped

**Comment by nwinch** [comment]
> I don't actually see this code as final, but as something that can inform our discussion in #4

@davidbanham I'll leave this to you to merge, if you want to involve more feedback.  It looks okay from my perspective.

**Comment by s-taylor** [comment]
I'll merge this once tests pass, just rebased onto master

**Comment by s-taylor** [comment]
LGTM 👍

**Pull request merged**
