### PR TITLE
Camelcaseify

### LINKED ISSUE #98: camelCase-ify
When scaffolding a controller using multiple words i.e. `redbeard model shift_template` the model name is used everywhere, file names, table names, variable names etc...

The naming convention should really be...
`name`: shiftTemplate
`pluralName`: shiftTemplates
`fileName:` shift_template.ext
`tableName:` shift_templates

All of these values can be derived from the name input.

### PR DESCRIPTION
**Pull request by s-taylor**
This PR generates additional names for projects / controllers so these can be used in variable names, table names etc... rather than everything being in snake case.

There is a bit of duplication in the names (see setNames function) but I think this is ok? I've used terms like tableName, dbName, projectName etc... but a lot of these are actually the same. The alternative would be to use a generic term like `snake_name`, `camelName`, `snake_name_plural`, `camelNamePlural` but this seemed kinda gross and requires more thinking when writing redbeard code.

Note: This PR builds on top of #105, this should be merged first.

This PR resolves #98

### CODE REVIEW

**Comment by s-taylor** [comment]
Thinking more about this, perhaps my alternative suggestion is actually better. We can then include `kebab-case` for urls as well and avoid repetition of the same variable with different titles.

**Comment by s-taylor** [comment]
This is now updated to match my proposal. I think this is much cleaner and also caters for url's being kebab-case which is nice!

**Comment by s-taylor** [comment]
This PR is ready for review for anyone who has time.

**Comment by davidbanham** [comment]
Big giant rebase to bring this up to date with master

This is going to be a pretty backwards-incompatible change. I don't think that means we shouldn't do it, we should just be aware.

**Comment by davidbanham** [comment]
This LGTM. @s-taylor can you please run an eye over this in case I nuked anything in the rebase?

**Pull request merged**
